name: Build

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEMESIS_VERSION_NAME: "autobuild-${{ github.sha }}"
      NEMESIS_BUILD_CHANNEL: "autobuild"
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Setup Java enviroment
        uses: actions/setup-java@v5.1.0
        with:
          distribution: temurin
          java-version: 21
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Download CB1060
        run: |
          mkdir -p libs
          curl -L -o libs/craftbukkit-1060.jar https://archive.org/download/craftbukkit1060/craftbukkit1-7-3%281060%29.jar
      
      - name: Build with Gradle
        run: ./gradlew buildAll


      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          path: build/libs/*.jar
